@NPos.WebApi_HostAddress = http://localhost:5045

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "051000012347",
  "name": "Raspberries",
  "category": "fruit"
}
###

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "012320012347",
  "name": "Gold Pan Brown Sugar & Cracked Pepper Rubbed Salmon, Ready to Cook",
  "category": "seafood"
}
###

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "180351000399",
  "name": "Cookie Dough Brownies",
  "category": ""
}
###