@NPos.WebApi_HostAddress = http://localhost:5045

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "051000012347",
  "name": "Raspberries",
  "category": "fruit"
}
###
