@NPos.WebApi_HostAddress = http://localhost:5045

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "051000012347",
  "name": "Raspberries",
  "categoryName": "fruit"
}
###

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "012320012347",
  "name": "Gold Pan Brown Sugar & Cracked Pepper Rubbed Salmon, Ready to Cook",
  "categoryName": "seafood"
}
###

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "180351000399",
  "name": "Cookie Dough Brownies",
  "categoryName": ""
}
###

POST {{NPos.WebApi_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "barcode": "180351000399",
  "name": "Cookie Dough Brownies"
}
###

POST {{NPos.WebApi_HostAddress}}/api/inventory/in
Content-Type: application/json
Accept: application/json

{
  "barcode": "012320012347",
  "cost": 10.25,
  "quantity": 10
}
###

POST {{NPos.WebApi_HostAddress}}/api/inventory/in
Content-Type: application/json
Accept: application/json

{
  "barcode": "051000012347",
  "cost": 5.0,
  "quantity": 20
}
###

POST {{NPos.WebApi_HostAddress}}/api/inventory/in
Content-Type: application/json
Accept: application/json

{
  "barcode": "180351000399",
  "cost": 1.0,
  "quantity": 1
}
###